AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lists active EC2 instances
Resources:
  GetInstances:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getinstances.getinstances.my_handler
      Role: arn:aws:iam::617287328294:role/ReadEC2StatusLambda
      Timeout: 300
      Runtime: python3.6
